image: golang:latest

variables:
  REPO_NAME: gitlab.com/aiarena/aiarena-discordbot

before_script:
  - apt-get update -qq
  - apt-get install -qq git unzip wget nodejs
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build

sonarqube-check:
  stage: test
  script:
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
    - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
    - sonar-scanner-4.2.0.1873-linux/bin/sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=aiarena-discordbot -Dsonar.sources=. -Dsonar.host.url=https://sonar.m1nd.io -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  only:
    - merge_requests
    - master

compile:
  stage: build
  script:
    - go get github.com/bwmarrin/discordgo && go get github.com/go-sql-driver/mysql && go get github.com/spf13/viper && go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/aiarena-discordbot
  artifacts:
    paths:
      - aiarena-discordbot
